seed: 42
batch_size: 512
wandb: 'disabled'
wandb_dir: /network/scratch/j/juan.duque/wandb/
use_transformer: False
sum_rewards: True
simultaneous: True
discrete: True
self_play: True
share_encoder: True
use_reward_loss: False
use_spr_loss: False

env:
  type: 'f1'
  batch: 2
  device: cuda

hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

# Architecture hyperparameters
network:
  _target_: src.networks.gru_network.GruIPD
  device: cuda

gru_model:
  _target_: src.models.models.GruModel
  in_size: 25
  device: cuda
  hidden_size: 64
  num_layers: 3

transformer_model:
  _target_: src.models.models.StableTransformer
  in_size: 3
  d_model: 64
  device: cuda
  dim_feedforward: 128
  num_layers: 1
  nhead: 4
  max_seq_len: 50
  dropout: 0.1

mlp_model:
  _target_: src.models.models.F1MLPModel
  in_size: 64
  device: cuda
  hidden_size: 128
  num_layers: 3

policy:
  _target_: src.agents.policies.F1NormalTanHPolicy
  log_std_min: -10.0
  log_std_max: 2.0
  device: cuda

linear_model:
  _target_: src.models.models.LinearModel
  in_size: 64
  out_size: 1
  device: cuda
  num_hidden: 2

spr_model:
  _target_: src.models.models.LinearModel
  in_size: 64
  out_size: 64
  device: cuda

optimizer_actor:
  _target_: torch.optim.Adam
  lr: 0.0001

optimizer_critic:
  _target_: torch.optim.Adam
  lr: 0.001

optimizer_reward:
  _target_: torch.optim.Adam
  lr: 1e-4

optimizer_spr:
  _target_: torch.optim.Adam
  lr: 1e-3

agent:
  _target_: src.agents.agents.AdvantageAlignmentAgent
  device: cuda

training:
  gamma: 0.96
  tau: 0.005
  max_traj_len: 50
  batch_size: 512 # Training batch size
  total_steps: 10000000 # Number of optimization steps to train for
  eval_every: 100 # Number of optimization steps before evaluation
  proximal: True
  clip_range: 0.15
  entropy_beta: 0.5
  vanilla: True
  updates_per_batch: 2
  use_mlm: True
  critic_loss_mode: 'MC'
  save_every: 200
  checkpoint_dir: './experiments'