seed: 41
batch_size: 512
wandb: 'offline'
wandb_tags: ['meltingpot', 'PPO', 'sum_rewards']
wandb_dir: /network/scratch/j/juan.duque/wandb/
use_transformer: True
sum_rewards: True
simultaneous: True
discrete: True
self_play: True
share_encoder: True
use_reward_loss: False
use_spr_loss: True
device: cuda
rb_size: 840
use_full_maps: False
hidden_size: 512
max_seq_len: 1500
max_cxt_len: 70
run_single_agent: False
debug_mode: False
use_ss_loss: False

env:
  type: 'meltingpot'
  batch: 6
  device: ${device}
  scenario: 'commons_harvest__open'
  num_agents: 7

hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

# Architecture hyperparameters
network:
  _target_: train.GruIPD
  device: ${device}

encoder:
  _target_: train.MeltingpotTransformer
  device: ${device}
  d_model: ${hidden_size}
  dim_feedforward: ${hidden_size}
  num_layers: 4
  max_seq_len: ${max_seq_len}
  attention_impl: 'original'

ss_module:
  _target_: train.SelfSupervisedModule
  n_actions: 8
  hidden_size: ${hidden_size}
  device: ${device}
  num_layers: 3

mlp_model:
  _target_: train.LinearModel
  in_size: ${hidden_size}
  device: ${device}
  hidden_size: ${hidden_size}
  num_layers: 3
  out_size: 8

policy:
  _target_: train.CategoricalPolicy
  device: ${device}

linear_model:
  _target_: train.LinearModel
  in_size: ${hidden_size}
  hidden_size: ${hidden_size}
  out_size: 1
  device: ${device}
  num_layers: 2

optimizer_actor:
  _target_: torch.optim.Adam
  lr: 5e-06

optimizer_critic:
  _target_: torch.optim.Adam
  lr: 1e-06

optimizer_ss:
  _target_: torch.optim.Adam
  lr: 1e-06

agent:
  _target_: train.AdvantageAlignmentAgent
  device: ${device}

training:
  gamma: 0.99
  tau: 0.005
  max_traj_len: ${max_seq_len}
  batch_size: 128 # Training batch size
  total_steps: 10000000 # Number of optimization steps to train for
  eval_every: 100 # Number of optimization steps before evaluation
  proximal: True
  clip_range: 0.2
  entropy_beta: 0.001
  updates_per_batch: 2
  kl_threshold: 0.05
  use_mlm: True
  critic_loss_mode: 'interpolate'
  save_every: 1000
  checkpoint_dir: './experiments'
  aa_weight: 0
  clip_grad_norm: 10
  ss_epochs: 1
  id_weight: 0
  spr_weight: 0
  normalize_advantages: True
  actor_loss_mode: 'integrated_aa'