seed: 41
batch_size: 512
wandb: 'online'
wandb_tags: ['meltingpot', 'PPO']
wandb_dir: /network/scratch/j/juan.duque/wandb/
use_transformer: True
sum_rewards: False
simultaneous: True
discrete: True
self_play: True
share_encoder: True
use_reward_loss: False
use_spr_loss: True
device: cuda
rb_size: 840
max_seq_len: 1000
max_cxt_len: 10
run_single_agent: True

env:
  type: 'meltingpot'
  batch: 12
  device: ${device}
  scenario: 'commons_harvest__open'
  num_agents: 7

hydra:
  output_subdir: null
  run:
    dir: /network/scratch/j/juan.duque/hydra/

# Architecture hyperparameters
network:
  _target_: train.GruIPD
  device: ${device}

encoder:
  _target_: train.MeltingpotTransformer
  device: ${device}
  d_model: 512
  dim_feedforward: 512 
  num_layers: 1
  max_seq_len: ${max_seq_len}

ss_module:
  _target_: train.SelfSupervisedModule
  n_actions: 8
  hidden_size: 512
  device: ${device}
  num_layers: 2

transformer_model:
  _target_: train.MeltingpotTransformer
  in_size: 50
  d_model: 512
  device: ${device}
  dim_feedforward: 512
  num_layers: 3
  num_embed_layers: 2
  nhead: 4
  max_seq_len: 50
  dropout: 0.1

mlp_model:
  _target_: train.LinearModel
  in_size: 512
  device: ${device}
  hidden_size: 512
  num_layers: 3
  out_size: 8

policy:
  _target_: train.CategoricalPolicy
  device: ${device}

linear_model:
  _target_: train.LinearModel
  in_size: 512
  hidden_size: 512
  out_size: 1
  device: ${device}
  num_layers: 2

optimizer_actor:
  _target_: torch.optim.Adam
  lr: 1e-06

optimizer_critic:
  _target_: torch.optim.Adam
  lr: 1e-06

optimizer_ss:
  _target_: torch.optim.Adam
  lr: 1e-06

agent:
  _target_: train.AdvantageAlignmentAgent
  device: ${device}

training:
  gamma: 0.96
  tau: 0.005
  max_traj_len: ${max_seq_len}
  batch_size: 128 # Training batch size
  total_steps: 10000000 # Number of optimization steps to train for
  eval_every: 100 # Number of optimization steps before evaluation
  proximal: True
  clip_range: 0.5
  entropy_beta: 0.005
  vanilla: True
  updates_per_batch: 2
  kl_threshold: 0.05
  use_mlm: True
  critic_loss_mode: 'MC'
  save_every: 1000
  checkpoint_dir: './experiments'
  aa_weight: 0
  clip_grad_norm: 500
  ss_epochs: 1
  ss_weight: 1