defaults:
  - eg.yaml
  - _self_

wandb: 'online'
wandb_dir: /home/mila/a/aghajohm/scratch/advantage-alignment/wandb_dir
hydra:
  run:
    dir:  /home/mila/a/aghajohm/scratch/advantage-alignment/hydra_dir

self_play: False
env:
  type: 'eg-obligated_ratio'
  device: cuda

network:
  device: cuda

gru_model:
  device: cuda

transformer_model:
  device: cuda

mlp_model:
  device: cuda

policy:
  device: cuda

linear_model:
  device: cuda

spr_model:
  device: cuda

agent:
  device: cuda


training:
  aa_weight: 10.0
