defaults:
  - eg.yaml
  - _self_

wandb: 'disabled'
wandb_dir: /Users/miladaghajohari/PycharmProjects/advantage-alignment/wandb_dir
hydra:
  run:
    dir:  /Users/miladaghajohari/PycharmProjects/advantage-alignment/hydra_dir

self_play: False

training:
  critic_loss_mode: 'MC'
  aa_weight: 10
