defaults:
  - eg.yaml
  - _self_

wandb: 'online'
wandb_dir: /home/mila/a/aghajohm/scratch/advantage-alignment/wandb_dir
hydra:
  run:
    dir:  /home/mila/a/aghajohm/scratch/advantage-alignment/hydra_dir

self_play: False

device: cuda

training:
  aa_weight: 10.0
