defaults:
  - meltingpot.yaml

hidden_size: 32

hydra:
  run:
    dir: /network/scratch/a/aghajohm/hydra_dir

wandb_dir:
  /network/scratch/a/aghajohm/wandb_dir

env:
  batch: 6

training:
  max_traj_len: 1000

optimizer_actor:
  lr: 1e-05

optimizer_critic:
  lr: 1e-05

optimizer_ss:
  lr: 1e-05



device: cuda

use_full_maps: False

share_encoder: False